config/routes.rb
Lelylan::Application.routes.draw do

  namespace :oauth do
    get    "authorization" => "oauth_authorize#show", defaults: { format: "html" }
    post   "authorization" => "oauth_authorize#create", defaults: { format: "html" }
    delete "authorization" => "oauth_authorize#destroy", defaults: { format: "html" }
    delete "token/:id" => "oauth_token#destroy", defaults: { format: "json" }
    post   "token" => "oauth_token#create", defaults: { format: "json" }
  end

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in"  => "sessions#new",     as: "log_in"

  get "sign_up" => "users#new",        as: "sign_up"
  get "users/show" => "users#show"
  get "users/edit" => "users#edit"

  resources :users
  resources :sessions
  resources :scopes

  resources :clients do
    put :block, on: :member
    put :unblock, on: :member
  end

  resources :accesses do
    put :block, on: :member
    put :unblock, on: :member
  end

  root :to => "sessions#new"

  # sample resources
  resources :pizzas, defaults: { format: "json" }
  resources :pastas, defaults: { format: "json" }

end

app/models/client.rb
# Application making protected resource requests on behalf of
# the resource owner and with its authorization

class Client
  include Mongoid::Document
  include Mongoid::Timestamps
  include Lelylan::Document::Base

  field :uri                                       # client identifier (internal)
  field :name                                      # client name
  field :created_from                              # user who created the client
  field :secret                                    # client secret
  field :site_uri                                  # client website
  field :redirect_uri                              # page called after authorization
  field :scope, type: Array, default: []           # raw scope with keywords
  field :scope_values, type: Array, default: []    # scope parsed as array of allowed actions
  field :info                                      # client additional info
  field :granted_times, type: Integer, default: 0  # tokens granted in the authorization step
  field :revoked_times, type: Integer, default: 0  # tokens revoked in the authorization step
  field :blocked, type: Time, default: nil         # blocks any request from the client

  attr_accessible :name, :site_uri, :redirect_uri, :info, :scope

  before_create  :random_secret
  before_destroy :clean

  validates :name, presence: true
  validates :uri, presence: true, url: true
  validates :created_from, presence: true, url: true
  validates :redirect_uri, presence: true, url: true


  # Block the client
  def block!
    self.blocked = Time.now
    self.save
    OauthToken.block_client!(self.uri)
    OauthAuthorization.block_client!(self.uri)
  end

  # Unblock the client
  def unblock!
    self.blocked = nil
    self.save
  end

  # Check if the status is or is not blocked
  def blocked?
    !self.blocked.nil?
  end

  # Increase the counter of resource owners granting the access
  # to the client
  def granted!
    self.granted_times += 1
    self.save
  end

  # Increase the counter of resource owners revoking the access
  # to the client
  def revoked!
    self.revoked_times += 1
    self.save
  end
  
  def scope_pretty
    separator = Oauth.settings["scope_separator"]
    scope.join(separator)
  end

  def scope_values_pretty
    separator = Oauth.settings["scope_separator"]
    scope_values.join(separator)
  end

  class << self

    # Filter to the client uri (internal identifier) and the
    # redirect uri
    def where_uri(client_uri, redirect_uri)
      where(uri: client_uri, redirect_uri: redirect_uri)
    end

    # Filter to the client secret and the redirect uri
    def where_secret(secret, client_uri)
      where(secret: secret, uri: client_uri)
    end

    # Filter to the client scope
    def where_scope(scope)
      all_in(scope_values: scope)
    end

    # Sync all clients with the correct exploded scope when a
    # scope is modified (changed or removed)
    def sync_clients_with_scope(scope)
      Client.all.each do |client|
        scope_string = client.scope.join(Oauth.settings["scope_separator"])
        client.scope_values = Oauth.normalize_scope(scope_string)
        client.save
      end
    end
  end


  private

    # TODO: use atomic updates
    # https://github.com/mongoid/mongoid/commit/aa2c388c71529bf4d987b286acfd861eaac530ce
    def block_tokens!
      OauthToken.where(client_uri: uri).map(&:block!)
    end

    def block_authorizations!
      OauthAuthorization.where(client_uri: uri).map(&:block!)
    end

    def random_secret
      self.secret = ActiveSupport::SecureRandom.hex(Oauth.settings["random_length"])
    end

    def clean
      OauthToken.where(client_uri: uri).destroy_all
      OauthAuthorization.where(client_uri: uri).destroy_all
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :find_clients
  before_filter :find_client, only: ["show", "edit", "update", "destroy", "block", "unblock"]
  before_filter :normalize_scope, only: ["create", "update"]
  before_filter :admin?, only: ["block", "unblock"]

  def index
  end

  def show
  end

  def new
    @client = Client.new
    @client.scope = ["all"]
  end

  def create
    @client = Client.new(params[:client])
    @client.created_from = current_user.uri
    @client.uri          = @client.base_uri(request)
    @client.scope_values = Oauth.normalize_scope(params[:client][:scope].clone)

    if @client.save
      redirect_to @client, notice: "Resource was successfully created."
    else
      render "new"
    end
  end

  def edit
  end

  def update
    @client.scope = params[:client][:scope]
    @client.scope_values = Oauth.normalize_scope(params[:client][:scope].clone)

    if @client.update_attributes(params[:client])
      flash.now.notice = "Resource was successfully updated."
      render "show"
    else
      render action: "edit"
    end
  end

  def destroy
    @client.destroy
    redirect_to(clients_url, notice: "Resource was successfully destroyed.")
  end

  # TODO: this is not REST way
  def block
    @client.block!
    redirect_to clients_url
  end

  def unblock
    @client.unblock!
    redirect_to clients_url
  end


  private 

    def find_clients
      if current_user.admin? 
        @clients = Client.criteria
      else 
        @clients = Client.where(created_from: current_user.uri)
      end
    end

    def find_client
      @client = @clients.id(params[:id]).first
      unless @client
        redirect_to root_path, alert: "Resource not found."
      end
    end

    def normalize_scope
      params[:client][:scope] = params[:client][:scope].split(Oauth.settings["scope_separator"])
    end 

    def admin?
      unless current_user.admin?
        flash.alert = "Unauthorized access."
        redirect_to root_path
        return false
      end
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
  def authorization_uri(client, scope)
    "/oauth/authorization?response_type=code&scope=#{scope}&client_id=#{client.uri}&redirect_uri=#{client.redirect_uri}"
  end
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>

  <% if @client.errors.any? %>
    <div id="error_explanation">
      <div><%= pluralize(@client.errors.count, "error") %> prohibited this resource from being saved</div>
      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :site_uri %><br />
    <%= f.text_field :site_uri %>
  </div>

  <div class="field">
    <%= f.label :redirect_uri %><br />
    <%= f.text_field :redirect_uri %>
  </div>

  <div class="field">
    <%= f.label :scope %> (separated by spaces)<br />
    <input id="client_scope" class="tags" name="client[scope]" size="30" type="text" value="<%=@client.scope_pretty%>">
  </div>

  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_field :info %>
  </div>

  <div class="actions">
    <%= f.submit nil, {class: "button"} %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h2>Editing Client</h2>

<div class="header_buttons button-group">
  <%= link_to 'Back', clients_path, class: "button icon arrowleft" %>
  <%= link_to 'Show', @client, class: "button" %>
</div>

<%= render 'form' %>

app/views/clients/index.html.erb
<h2>Show Clients</h2>
<div class="header_buttons">
  <%= link_to 'Create a new client', new_client_path, class: "button icon add" %>
</div>

<table>
  <tr>
    <% if current_user.admin? %>
      <th>User</th>
    <% end %>
    <th>Name</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <% if current_user.admin? %>
      <td><%= link_to User, client.created_from %></td>
    <% end %>
    <td><%= client.name %></td>
    <% unless current_user.admin? %>
      <td><%= client.blocked? ? "Not Active" : "Active" %></td>
    <% end %>
    <td><%= link_to 'Show', client, class: "button" %></td>
    <td><%= link_to 'Edit', edit_client_path(client), class: "button" %></td>
    <td><%= link_to 'Destroy', client, confirm: 'Are you sure?', method: :delete, class: "button danger" %></td>
    <% if current_user.admin? %>
      <% if client.blocked? %>
        <td><%= link_to 'Unblock!', unblock_client_path(client), method: :put, class: "button danger icon unlock" %></td>
      <% else %>
        <td><%= link_to 'Block!', block_client_path(client), method: :put, class: "button danger icon lock" %></td>
      <% end %>
    <% end %>

  </tr>
<% end %>
</table>

<br/>

app/views/clients/new.html.erb
<h2>New Client</h2>

<div class="button-group header_buttons">
  <%= link_to 'Back', clients_path, class: "button icon arrowleft" %>
</div>

<%= render 'form' %>

app/views/clients/show.html.erb
<h2>Show Client</h2>

<div class="field_show">
  <b>Client URI:</b>
  <%= @client.uri %>
</div>

<div class="field_show">
  <b>Name:</b>
  <%= @client.name %>
</div>

<div class="field_show">
  <b>Secret:</b>
  <%= @client.secret %>
</div>

<div class="field_show">
  <b>Site URI:</b>
  <%= @client.site_uri %>
</div>

<div class="field_show">
  <b>Redirect URI:</b>
  <%= @client.redirect_uri %>
</div>

<div class="field_show">
  <b>Scope:</b>
  <%= @client.scope_pretty %> 
  <span class="details">(includes <%= @client.scope_values_pretty %>)</span>
</div>

<div class="field_show">
  <b>Info:</b>
  <%= @client.info %>
</div>

<div class="actions button-container footer_buttons">
  <div class="button-group">
    <%= link_to 'Back', clients_path, class: "button icon arrowleft" %>
    <%= link_to 'Edit', edit_client_path(@client), class: "button" %>
    <%= link_to 'Destroy', @client, :confirm => 'Are you sure?', :method => :delete, class: "button danger" %>
  </div>

  <div class="button-group">
    <%= link_to 'Simulate Authorization', authorization_uri(@client, "all"), class: "button icon search" %>
  </div>
</div>