config/routes.rb
Lelylan::Application.routes.draw do

  namespace :oauth do
    get    "authorization" => "oauth_authorize#show", defaults: { format: "html" }
    post   "authorization" => "oauth_authorize#create", defaults: { format: "html" }
    delete "authorization" => "oauth_authorize#destroy", defaults: { format: "html" }
    delete "token/:id" => "oauth_token#destroy", defaults: { format: "json" }
    post   "token" => "oauth_token#create", defaults: { format: "json" }
  end

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in"  => "sessions#new",     as: "log_in"

  get "sign_up" => "users#new",        as: "sign_up"
  get "users/show" => "users#show"
  get "users/edit" => "users#edit"

  resources :users
  resources :sessions
  resources :scopes

  resources :clients do
    put :block, on: :member
    put :unblock, on: :member
  end

  resources :accesses do
    put :block, on: :member
    put :unblock, on: :member
  end

  root :to => "sessions#new"

  # sample resources
  resources :pizzas, defaults: { format: "json" }
  resources :pastas, defaults: { format: "json" }

end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController

  before_filter :find_accesses
  before_filter :find_access, except: "index"

  def index
  end

  def show
  end

  def block
    @access.block!
    redirect_to accesses_url
  end

  def unblock
    @access.unblock!
    redirect_to accesses_url
  end


  private 
  
    def find_accesses
      @accesses = OauthAccess.where(resource_owner_uri: current_user.uri)
    end

    def find_access
      @access = @accesses.id(params[:id]).first
      unless @access
        redirect_to root_path, alert: "Resource not found."
      end
    end

    # TODO: change this behavior with a simple redirect
    def resource_not_found
      flash.now.alert = "notifications.document.not_found"
      @info = { id: params[:id] }
      render "shared/html/404" and return
    end 

end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/views/accesses/index.html.erb
<h2>Show Accesses</h2>

<table>
  <tr>
    <th>Client URI</th>
    <th></th>
    <th></th>
  </tr>

<% @accesses.each do |access| %>
  <tr>
    <td><%= access.client_uri %></td>
    <td><%= link_to 'Show stats', access_path(access), class: "button icon settings" %></td>
   
    <% if access.blocked? %>
      <td><%= link_to 'Unblock!', unblock_access_path(access), method: :put, class: "button danger" %></td>
    <% else %>
      <td><%= link_to 'Block!', block_access_path(access), method: :put, class: "button danger" %></td>
    <% end %>

  </tr>
<% end %>
</table>

<br/>

app/views/accesses/show.html.erb
<h2>Show Access</h2>

<div class="field_show">
  <b>Client URI:</b>
  <%= @access.client_uri %>
</div>

<div class="field_show">
  <b>Today requests:</b>
  <%= @access.daily_requests.times %>
</div>

<div id="chart" style="width: 100%; height: 250px"></div>

<div class="footer_buttons"> 
<%= link_to 'Back', accesses_path, class: "button icon arrowleft" %>
<% if @access.blocked? %>
  <%= link_to 'Unblock!', unblock_access_path(@access), method: :put, class: "button danger" %>
<% else %>
  <%= link_to 'Block!', block_access_path(@access), method: :put, class: "button danger" %>
<% end %>
<div>


<script>
  $(document).ready(function() {
    createChart(
      <%=raw @access.chart_days %>,
      <%= @access.chart_times.to_json %>,
      "<%= @access.client_uri %>"
    )  
  });
</script>