config/routes.rb
Lelylan::Application.routes.draw do

  namespace :oauth do
    get    "authorization" => "oauth_authorize#show", defaults: { format: "html" }
    post   "authorization" => "oauth_authorize#create", defaults: { format: "html" }
    delete "authorization" => "oauth_authorize#destroy", defaults: { format: "html" }
    delete "token/:id" => "oauth_token#destroy", defaults: { format: "json" }
    post   "token" => "oauth_token#create", defaults: { format: "json" }
  end

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in"  => "sessions#new",     as: "log_in"

  get "sign_up" => "users#new",        as: "sign_up"
  get "users/show" => "users#show"
  get "users/edit" => "users#edit"

  resources :users
  resources :sessions
  resources :scopes

  resources :clients do
    put :block, on: :member
    put :unblock, on: :member
  end

  resources :accesses do
    put :block, on: :member
    put :unblock, on: :member
  end

  root :to => "sessions#new"

  # sample resources
  resources :pizzas, defaults: { format: "json" }
  resources :pastas, defaults: { format: "json" }

end

app/models/scope.rb
class Scope
  include Mongoid::Document
  include Mongoid::Timestamps
  include Lelylan::Document::Base

  field :name
  field :uri
  field :values, type: Array, default: []

  attr_accessible :name

  validates :name, presence: true
  validates :values, presence: true
  validates :uri, url: true

  def normalize(val)
    separator = Oauth.settings["scope_separator"]
    val = val.split(separator)
  end

  def values_pretty
    separator = Oauth.settings["scope_separator"]
    values.join(separator)
  end

  class << self
    # Sync all scopes with the correct exploded scope when a
    # scope is modified (changed or removed)
    def sync_scopes_with_scope(scope)
      scopes_to_sync = any_in(scope: [scope])
      scopes_to_sync.each do |client|
        scope.values = Oauth.normalize_scope(scope.values)
        scope.save
      end
    end
  end
end

app/controllers/scopes_controller.rb
class ScopesController < ApplicationController
 
  before_filter :admin?
  before_filter :find_resource, only: ["show", "edit", "update", "destroy"]
  after_filter  :sync_existing_scopes, only: ["update", "destroy"] 

  def index
    @scopes = Scope.all
  end

  def show
  end

  def new
    @scope = Scope.new
  end

  def create
    @scope        = Scope.new(params[:scope])
    @scope.uri    = @scope.base_uri(request)
    @scope.values = @scope.normalize(params[:scope][:values])

    if @scope.save
      redirect_to(@scope, notice: "Resource was successfully created.")
    else
      render action: "new"
    end
  end

  def edit
  end

  def update
    @scope.values = @scope.normalize(params[:scope][:values])

    if @scope.update_attributes(params[:scope])
      render("show", notice: "Resource was successfully updated.")
    else
      render action: "edit"
    end
  end

  def destroy
    @scope.destroy
    redirect_to(scopes_url, notice: "Resource was successfully destroyed.")
  end


  private

    def find_resource
      @scope = Scope.criteria.id(params[:id]).first
      unless @scope
        redirect_to root_path, alert: "Resource not found."
      end        
    end

    # TODO: put into a background process
    def sync_existing_scopes
      Client.sync_clients_with_scope(@scope.name)
    end

    def admin?
      unless current_user.admin?
        flash.alert = "Unauthorized access."
        redirect_to root_path
        return false
      end
    end

end

app/helpers/scopes_helper.rb
module ScopesHelper
end

app/views/scopes/_form.html.erb
<%= form_for(@scope) do |f| %>

  <% if @scope.errors.any? %>
    <div id="error_explanation">
      <div><%= pluralize(@scope.errors.count, "error") %> prohibited this resource from being saved</div>
      <ul>
      <% @scope.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :values %> (separated by spaces)<br />
    <input id="scope_values" class="tags" name="scope[values]" size="30" type="text" value="<%=@scope.values.join(" ") if @scope.values%>">
  </div>

  <div class="actions">
    <%= f.submit nil, {class: "button" } %>
  </div>
<% end %>

app/views/scopes/edit.html.erb
<h2>Editing Scope</h2>

<div class="button-group header_buttons">
  <%= link_to 'Back', scopes_path, class: "button icon arrowleft" %>
  <%= link_to 'Show', @scope, class: "button" %>
</div>

<%= render 'form' %>

app/views/scopes/index.html.erb
<h2>Show Scope</h2>

<div class="header_buttons">
  <%= link_to 'Create a new scope', new_scope_path, class: "button icon add" %>
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Values</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scopes.each do |scope| %>
  <tr>
    <td><b><%= scope.name %></b></td>
    <td><%= scope.values_pretty %></td>
    <td><%= link_to 'Show', scope, class: "button" %></td>
    <td><%= link_to 'Edit', edit_scope_path(scope), class: "button" %></td>
    <td><%= link_to 'Destroy', scope, :confirm => 'Are you sure?', :method => :delete, class: "button danger" %></td>
  </tr>
<% end %>
</table>

<br/>

app/views/scopes/new.html.erb
<h2>New Scope</h2>

<div class="button-group header_buttons">
  <%= link_to 'Back', scopes_path, class: "button icon arrowleft" %>
</div>

<%= render 'form' %>

app/views/scopes/show.html.erb
<h2>Show Scope</h2>

<div class="field_show">
  <b>Name:</b>
  <%= @scope.name %>
</div>

<div class="field_show">
  <b>Values:</b>
  <%= @scope.values_pretty %>
  <span class="details">(includes <%= Oauth.normalize_scope(@scope.values_pretty).join(" ") %></span>
</div>


<div class="button-group footer_buttons">
<%= link_to 'Back', scopes_path, class: "button icon arrowleft" %> 
<%= link_to 'Edit', edit_scope_path(@scope), class: "button" %>
<%= link_to 'Destroy', @scope, :confirm => 'Are you sure?', :method => :delete, class: "button danger" %>
</div>