config/routes.rb
Lelylan::Application.routes.draw do

  namespace :oauth do
    get    "authorization" => "oauth_authorize#show", defaults: { format: "html" }
    post   "authorization" => "oauth_authorize#create", defaults: { format: "html" }
    delete "authorization" => "oauth_authorize#destroy", defaults: { format: "html" }
    delete "token/:id" => "oauth_token#destroy", defaults: { format: "json" }
    post   "token" => "oauth_token#create", defaults: { format: "json" }
  end

  get "log_out" => "sessions#destroy", as: "log_out"
  get "log_in"  => "sessions#new",     as: "log_in"

  get "sign_up" => "users#new",        as: "sign_up"
  get "users/show" => "users#show"
  get "users/edit" => "users#edit"

  resources :users
  resources :sessions
  resources :scopes

  resources :clients do
    put :block, on: :member
    put :unblock, on: :member
  end

  resources :accesses do
    put :block, on: :member
    put :unblock, on: :member
  end

  root :to => "sessions#new"

  # sample resources
  resources :pizzas, defaults: { format: "json" }
  resources :pastas, defaults: { format: "json" }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"> 
  <title>Rest OAuth 2.0 Server</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery.tagsinput.js", "highcharts.js" %>
  <%= csrf_meta_tag %>
</head>

<body">
  <div class="container">
    <% unless request.path == oauth_authorization_path %>
      <a class="ribbon" href="https://github.com/lelylan/rest-oauth2-server" target="_blank"><img src="http://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>

      <div class="header">
        <h1>Rest OAuth 2.0 Server</h1>
        <p>
          <b><a href="https://github.com/lelylan/rest-oauth2-server" title="GitHub repository">Rest OAuth 2.0 Server</a> 
            let you open up your API and manage end-user authentication and client application authorization 
            implementing the OAuth 2.0 Specifications (draft 13). Read more on <a href="https://github.com/lelylan/rest-oauth2-server" title="GitHub readme">Github</a>
          </b>
        </p>
      </div>
    <% end %>
      <div class="navigation">
        <% if current_user %>
          <div style="float: right">
            Logged in as <%= current_user.email %>.
            <%= link_to "Log out", log_out_path %>
          </div>
          <div>
            <%= link_to("Home", current_user)  %> |
            <%= link_to("Accesses", accesses_path)  %> |
            <%= link_to("Clients", clients_path)  %>
            <% if current_user.admin? %> |
              <%= link_to("Users", users_path) %> |
              <%= link_to("Scopes", scopes_path) %> 
            <% end %>
          </div>
        <% else %>
          <%= link_to "Sign up", sign_up_path %> or
          <%= link_to "log in", log_in_path %>
        <% end %>
      </div>
      <br/>


    <% if flash.notice %>
      <div class="flash_notice">
        <%= flash.notice %>
      </div>
    <% end %>

    <% if flash.alert %>
      <div class=flash_alert>
        <%= flash.alert %>
        <% if @info %>
          <p>Additional information: 
          <%= @info.to_json%>
          </p>
        <% end %>
      </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>